name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://github.io
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Construir o Site (Build)
        # É aqui que o robô puxa a chave que você vai esconder no GitHub
        env:
          VITE_NASA_API_KEY: ${{ secrets.VITE_NASA_API_KEY }}
        run: npm run build

      - name: Enviar para o GitHub Pages
        uses: actions/configure-pages@v4
      
      - name: Upload dos Arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Publicar Link
        uses: actions/deploy-pages@v4
